#!/usr/bin/env bash
#
# setup-dhcp-server.sh: configure a Raspberry Pi 5 as a DHCP server on eth0
# using NetworkManager (static IP) and dnsmasq (DHCP-only).
#
# The Pi is assigned the .1 address of the supplied subnet, and dnsmasq
# serves leases in the .100-.254 range. dnsmasq is configured with
# bind-dynamic so DHCP service starts whenever the Ethernet cable is
# plugged in, even long after boot, with no restart required.
#
# Usage: sudo ./setup-dhcp-server.sh <subnet/prefix> [interface]
#   e.g. sudo ./setup-dhcp-server.sh 192.168.4.0/24
#        sudo ./setup-dhcp-server.sh 10.0.7.0/24 eth0
#
# Prerequisite: the Pi must have internet access (e.g. via WiFi) so that
# dnsmasq can be installed.
set -euo pipefail

usage() {
    echo "Usage: sudo $0 <subnet/prefix> [interface]" >&2
    echo "  e.g. sudo $0 192.168.4.0/24" >&2
    exit 1
}

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: this script must be run as root (use sudo)." >&2
    exit 1
fi

[ $# -ge 1 ] || usage
SUBNET="$1"
INTERFACE="${2:-eth0}"

# Validate subnet format: a.b.c.0/24 (only /24 subnets are supported)
if ! echo "${SUBNET}" | grep -Eq '^([0-9]{1,3}\.){2}[0-9]{1,3}\.0/24$'; then
    echo "Error: subnet must be of the form a.b.c.0/24 (e.g. 192.168.4.0/24)" >&2
    exit 1
fi

PREFIX="$(echo "${SUBNET}" | cut -d/ -f1 | cut -d. -f1-3)"
SERVER_IP="${PREFIX}.1"
RANGE_START="${PREFIX}.100"
RANGE_END="${PREFIX}.254"
NETMASK="255.255.255.0"
LEASE_TIME="10m"

echo "Configuring ${INTERFACE} with static IP ${SERVER_IP}/24"
echo "DHCP range: ${RANGE_START} - ${RANGE_END} (lease ${LEASE_TIME})"

# Find the NetworkManager connection for the interface
UUID="$(nmcli -g UUID,DEVICE,TYPE connection show | awk -F: -v dev="${INTERFACE}" '$2 == dev && $3 == "802-3-ethernet" {print $1; exit}')"
if [ -z "${UUID}" ]; then
    # Fall back to any ethernet connection profile if the device is down
    UUID="$(nmcli -g UUID,TYPE connection show | awk -F: '$2 == "802-3-ethernet" {print $1; exit}')"
fi
if [ -z "${UUID}" ]; then
    echo "Error: no ethernet connection profile found (nmcli connection show)." >&2
    exit 1
fi

echo "Using NetworkManager connection ${UUID}"
nmcli connection modify "${UUID}" ipv4.addresses "${SERVER_IP}/24"
nmcli connection modify "${UUID}" ipv4.method manual
nmcli connection modify "${UUID}" ipv4.never-default true
nmcli connection modify "${UUID}" connection.autoconnect yes
nmcli connection up "${UUID}" || echo "Note: connection did not come up (cable unplugged?); it will activate when a cable is connected."

echo "Installing dnsmasq"
apt-get update
apt-get install -y dnsmasq

echo "Writing /etc/dnsmasq.d/${INTERFACE}-dhcp.conf"
cat > "/etc/dnsmasq.d/${INTERFACE}-dhcp.conf" <<EOF
# DHCP-only server on ${INTERFACE} (generated by setup-dhcp-server.sh)
interface=${INTERFACE}
bind-dynamic
dhcp-range=${RANGE_START},${RANGE_END},${NETMASK},${LEASE_TIME}
dhcp-authoritative
# Disable DNS: DHCP only
port=0
EOF

echo "Enabling and starting dnsmasq"
systemctl enable --now dnsmasq
systemctl restart dnsmasq

echo "Done. Verify with: journalctl -u dnsmasq | grep DHCP"
